[app]
name = "AxelTTS"
version = "v0.2.2"

[tts]
# Volume is a relative multiplier and must be greater than 0
playback_volume = 1
# Speed is a relative multiplier and must be greater than or equal to 1
playback_speed = 1
# Languages that are not translated and read in that language.
# English is the default language and should not be removed.
# For most of the language codes, read https://cloud.google.com/translate/docs/languages,
# but not all of them are supported 
allowed_languages = ["en"]
# Localized accent used for the english voice. 
# For possible values, read https://gtts.readthedocs.io/en/latest/module.html#localized-accents
# This accent is used by default for the intro ("<user> from <platform> said")
default_english_accent = "ca"
# English accents that are randomly used for reading english messages.
# If empty, default_english_accent is used.
random_user_english_accents = ["com", "com.au", "ie", "co.uk"]
# Threshold used to determine when to translate a message. Value is between 0 and 1.
translation_confidence_threshold = 0.5
# Regex rules for filtering messages. Filtered messages are not added to the TTS queue.
filter = [
    # Any messages with length 250 or over
    ".{250,}",
    # Any word in the message is 20 characters or longer
    "\\b\\w{20,}\\b",
    # Any word contains a character that is repeated 6 or more times in a row
    "(.)\\1{5,}",
    # Any word contains two characters that are repeated 4 or more times in a row (example: tstststs)
    "(.)(.)(\\1\\2){3,}",
    # Any word is repeated 4 or more times in a row
    "\\b(\\w+)\\b(\\s+\\1){3,}",
]
# Time between messages scales based on number of messages in the queue. When there is only one message
# this is the wait time between the possible next message that might come. The wait time
# scales down linearly towards 0. Make this value 0 to make it read messages as fast as possible all the time.
max_time_between_messages = 2.0
# The size of the queue to be for the above wait time to have scaled to 0. The wait time with queue size N is
# max(0, max_time_between_messages * (1 - N / no_wait_queue_size)). Make this a large number to disable scaling.
no_wait_queue_size = 5

# Below here platform specific rules can be configured. You can safely remove the examples in your own config.
# Under [<platform>] in ignored_users, you can list all the usernames whose messages should be ignored on that platform.
# This is good for ignoring messages from bots for example.
# Under [<platform>.nicknames], you can set nicknames for users. The nickname is read intead.
# All platform and user names are treated as lowercase.
[twitch]
ignored_users = ["example_bot"]

[twitch.nicknames]
"日本語" = "japanese name"
"cool_username" = "cooler username"

[youtube.nicknames]
"cool_username_yt" = "cooler username"
